<!DOCTYPE html>
<head><link rel="stylesheet" href="debtmasters.css" <!-- CSS only -->
    <li><a href="file:///C:/Users/27834/OneDrive/Desktop/ROUX/Debt%20Masters.html"><h2>HOME</h2></a></li>
    <!--a href="file:///C:/Users/27834/OneDrive/Desktop/ROUX/Owner%20deptmasters.html"><h2>Owner</h2></a-->
    <style>
    body{
        background-image: repeating-linear-gradient(rgb(0, 238, 255), rgb(0, 255, 234) 10%, rgb(179, 255, 255) 20%);
        }</style>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">>
</head>
<body>
<h1><center>About</center></h1>
       <p>
        <center>
            At Debt Masters we can help you to get immediate Protection for Debt Stress, Blacklisting, Legal Act</p>

            <p>Page · Credit counselling service</p>
            
            <p>11A, 2nd Avenue, Boston, Bellville, Cape Town, South Africa</p>
            
            <p>021 001 2631</p>
            
            <p>johann@debtmasters.biz</p>
        <center>
        <p>
        <p> </p>
        <center><img src="C:\Users\27834\OneDrive\Desktop\ROUX\Scratch\photos\financial-system.png"></center>
        <h1>Offerings</h1>
        <p>Debt Masters offer a personalised debt repayment plan:</p>
            <p>🧿 Immediate relief and improved cash flow</p>
            <p>🧿 Reduced monthly instalments for all your loans and accounts</p>
            <p>🧿 Assets protected against repossession</p>
            <p>👉 Click on the message button below and we will contact you!</p>
            </p>
        </body>
